### ISSUE TITLE
Interruptability and Recoverability of --reindexchainstate

### ISSUE THREAD

**Issue by emergent-reasons** [gcash/bchd#166]
I did a `--reindexchainstate` and needed to reboot for an unrelated issue. As I see it, two issues emerged. This is not causing a problem for me so there is no urgency on my side. I am not sure how many people would run into this but I assume not many.

### Issue 1: Fail to interrupt utxo reindex:

- `bchd --externalip <ip> --addrindex --txindex --maxpeers 30 --targetoutboundpeers 10 --reindexchainstate`
- `ctrl-c` interrupted it and it goes into shutdown mode
- the process does not terminate and the utxo reindex seems to continue with normal high CPU usage
- `ctrl-c` again says it is already shutting down but nothing else seems to change
- terminate bchd and reboot pc
- The reindex did not go to completion so I am not sure if the below issue would have happened without terminating bchd.

### Issue 2: Out of Memory after reboot:

- laptop:
    - `bchd` built from 2cb2a8c6
    - linux mint 19
    - kernel 4.15.0-42
    - 2 cores
    - 16GB
    - plenty of ssd space remaining

- restart `bchd` (same as before but without `--reindexchainstate`)
- it ran for an unknown length of time overnight (no additional log entries) before crashing OOM

```
2018-12-13 00:34:06.953 [INF] BCHD: Loading block database from '/home/alien/.bchd/data/mainnet/blocks_ffldb'
2018-12-13 00:34:07.381 [INF] BCHD: Block database loaded
2018-12-13 00:34:07.399 [INF] INDX: Transaction index is enabled
2018-12-13 00:34:07.399 [INF] INDX: Address index is enabled
2018-12-13 00:34:07.399 [INF] INDX: Committed filter index is enabled
2018-12-13 00:34:07.405 [INF] CHAN: Loading block index...
2018-12-13 00:34:10.366 [INF] CHAN: Reconstructing UTXO state after unclean shutdown. This may take a long time...
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0xa9a3be, 0x16)
	/usr/local/go/src/runtime/panic.go:608 +0x72
runtime.sysMap(0xc3b4000000, 0x310000000, 0x10a2318)
	/usr/local/go/src/runtime/mem_linux.go:156 +0xc7
runtime.(*mheap).sysAlloc(0x1088ca0, 0x310000000, 0x7f6aa97c94d8, 0x7f6ae6da3d00)
	/usr/local/go/src/runtime/malloc.go:619 +0x1c7
runtime.(*mheap).grow(0x1088ca0, 0x187000, 0x0)
	/usr/local/go/src/runtime/mheap.go:920 +0x42
runtime.(*mheap).allocSpanLocked(0x1088ca0, 0x187000, 0x10a2328, 0x20305100000000)
	/usr/local/go/src/runtime/mheap.go:848 +0x337
runtime.(*mheap).alloc_m(0x1088ca0, 0x187000, 0xffffffffffff0100, 0x7f6ae6da3db8)
	/usr/local/go/src/runtime/mheap.go:692 +0x119
runtime.(*mheap).alloc.func1()
	/usr/local/go/src/runtime/mheap.go:759 +0x4c
runtime.(*mheap).alloc(0x1088ca0, 0x187000, 0x7f6ae6010100, 0x417f05)
	/usr/local/go/src/runtime/mheap.go:758 +0x8a
runtime.largeAlloc(0x30e000000, 0x450001, 0x7f6b18797d80)
	/usr/local/go/src/runtime/malloc.go:1019 +0x97
runtime.mallocgc.func1()
	/usr/local/go/src/runtime/malloc.go:914 +0x46
runtime.systemstack(0x0)
	/usr/local/go/src/runtime/asm_amd64.s:351 +0x66
runtime.mstart()
	/usr/local/go/src/runtime/proc.go:1229

goroutine 1 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:311 fp=0xc009b7eff8 sp=0xc009b7eff0 pc=0x45b4a0
runtime.mallocgc(0x30e000000, 0xa24b20, 0x7f6aab7da301, 0xc009b7f0e0)
	/usr/local/go/src/runtime/malloc.go:913 +0x896 fp=0xc009b7f098 sp=0xc009b7eff8 pc=0x40de06
runtime.newarray(0xa24b20, 0x2200000, 0xc15d990300)
	/usr/local/go/src/runtime/malloc.go:1048 +0x6a fp=0xc009b7f0c8 sp=0xc009b7f098 pc=0x40e1da
runtime.makeBucketArray(0x9ca2a0, 0x92c38c96d4676c19, 0x0, 0x403592, 0xc009b7f20c)
	/usr/local/go/src/runtime/map.go:355 +0x184 fp=0xc009b7f100 sp=0xc009b7f0c8 pc=0x40f0a4
runtime.hashGrow(0x9ca2a0, 0xc00013cba0)
	/usr/local/go/src/runtime/map.go:963 +0x89 fp=0xc009b7f150 sp=0xc009b7f100 pc=0x4108f9
runtime.mapassign(0x9ca2a0, 0xc00013cba0, 0xc009b7f20c, 0x10a16e0)
	/usr/local/go/src/runtime/map.go:623 +0x2af fp=0xc009b7f1d8 sp=0xc009b7f150 pc=0x40fa6f
github.com/gcash/bchd/blockchain.(*utxoCache).addEntry(0xc0000a67e0, 0x68115a094dff0a73, 0x59c2ffc8329d91f2, 0x56b46ada8b0c3c70, 0xa9c354ddaf295d22, 0xc000000001, 0xc141e2a720, 0x1, 0x0, 0x0)
	/home/alien/go/src/github.com/gcash/bchd/blockchain/utxocache.go:416 +0x140 fp=0xc009b7f298 sp=0xc009b7f1d8 pc=0x796a20
github.com/gcash/bchd/blockchain.disconnectTransactions(0xc72ee0, 0xc0000a67e0, 0xc128fa8960, 0xc1a0e3c000, 0x14d5, 0x14d5, 0x0, 0x0)
	/home/alien/go/src/github.com/gcash/bchd/blockchain/utxoviewpoint.go:336 +0x204 fp=0xc009b7f3a0 sp=0xc009b7f298 pc=0x79a544
github.com/gcash/bchd/blockchain.(*utxoCache).rollBackBlock(0xc0000a67e0, 0xc128fa8960, 0xc1a0e3c000, 0x14d5, 0x14d5, 0x14d5, 0x0)
	/home/alien/go/src/github.com/gcash/bchd/blockchain/utxocache.go:632 +0x5f fp=0xc009b7f3f0 sp=0xc009b7f3a0 pc=0x797c4f
github.com/gcash/bchd/blockchain.(*utxoCache).InitConsistentState.func3(0xc784a0, 0xc19a561180, 0xc00584c3f0, 0xc000000008, 0xc01baf8340, 0x7a6000)
	/home/alien/go/src/github.com/gcash/bchd/blockchain/utxocache.go:727 +0x103 fp=0xc009b7f460 sp=0xc009b7f3f0 pc=0x7a5f13
github.com/gcash/bchd/blockchain.(*utxoCache).InitConsistentState.func4(0xc784a0, 0xc19a561180, 0xc19a561180, 0x0)
	/home/alien/go/src/github.com/gcash/bchd/blockchain/utxocache.go:747 +0x4e fp=0xc009b7f4a8 sp=0xc009b7f460 pc=0x7a604e
github.com/gcash/bchd/database/ffldb.(*db).Update(0xc00006e240, 0xc192180a20, 0x0, 0x0)
	/home/alien/go/src/github.com/gcash/bchd/database/ffldb/db.go:1960 +0x9b fp=0xc009b7f4f8 sp=0xc009b7f4a8 pc=0x8256bb
github.com/gcash/bchd/blockchain.(*utxoCache).InitConsistentState(0xc0000a67e0, 0xc0061ff9b0, 0xc00002e120, 0x2, 0x0)
	/home/alien/go/src/github.com/gcash/bchd/blockchain/utxocache.go:745 +0x573 fp=0xc009b7f5f8 sp=0xc009b7f4f8 pc=0x798273
github.com/gcash/bchd/blockchain.New(0xc000146480, 0xc000146480, 0x18, 0x0)
	/home/alien/go/src/github.com/gcash/bchd/blockchain/chain.go:2106 +0x69e fp=0xc009b7f898 sp=0xc009b7f5f8 pc=0x78572e
main.newServer(0xc00005c260, 0x1, 0x1, 0xc74c20, 0xc00006e240, 0x1076460, 0xc00002e120, 0xc0001366b0, 0xc0001366a0, 0xc0001346a0)
	/home/alien/go/src/github.com/gcash/bchd/server.go:2681 +0x9b6 fp=0xc009b7fe10 sp=0xc009b7f898 pc=0x927636
main.bchdMain(0x0, 0x0, 0x0)
	/home/alien/go/src/github.com/gcash/bchd/bchd.go:153 +0x69f fp=0xc009b7ff28 sp=0xc009b7fe10 pc=0x8e272f
main.main()
	/home/alien/go/src/github.com/gcash/bchd/bchd.go:335 +0xd0 fp=0xc009b7ff98 sp=0xc009b7ff28 pc=0x8e3df0
runtime.main()
	/usr/local/go/src/runtime/proc.go:201 +0x207 fp=0xc009b7ffe0 sp=0xc009b7ff98 pc=0x42f4d7
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc009b7ffe8 sp=0xc009b7ffe0 pc=0x45d581

goroutine 8 [syscall, 303 minutes]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:139 +0x9c
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
	/usr/local/go/src/os/signal/signal_unix.go:29 +0x41

goroutine 9 [select, 303 minutes]:
main.interruptListener.func1(0xc00002e120)
	/home/alien/go/src/github.com/gcash/bchd/signal.go:31 +0x113
created by main.interruptListener
	/home/alien/go/src/github.com/gcash/bchd/signal.go:25 +0x58

goroutine 10 [select]:
github.com/gcash/bchd/vendor/github.com/btcsuite/goleveldb/leveldb/util.(*BufferPool).drain(0xc0000f2000)
	/home/alien/go/src/github.com/gcash/bchd/vendor/github.com/btcsuite/goleveldb/leveldb/util/buffer_pool.go:206 +0x12a
created by github.com/gcash/bchd/vendor/github.com/btcsuite/goleveldb/leveldb/util.NewBufferPool
	/home/alien/go/src/github.com/gcash/bchd/vendor/github.com/btcsuite/goleveldb/leveldb/util/buffer_pool.go:237 +0x177

goroutine 50 [select]:
github.com/gcash/bchd/vendor/github.com/btcsuite/goleveldb/leveldb.(*DB).compactionError(0xc00014a820)
	/home/alien/go/src/github.com/gcash/bchd/vendor/github.com/btcsuite/goleveldb/leveldb/db_compaction.go:90 +0xd3
created by github.com/gcash/bchd/vendor/github.com/btcsuite/goleveldb/leveldb.openDB
	/home/alien/go/src/github.com/gcash/bchd/vendor/github.com/btcsuite/goleveldb/leveldb/db.go:142 +0x40c

goroutine 51 [select]:
github.com/gcash/bchd/vendor/github.com/btcsuite/goleveldb/leveldb.(*DB).mpoolDrain(0xc00014a820)
	/home/alien/go/src/github.com/gcash/bchd/vendor/github.com/btcsuite/goleveldb/leveldb/db_state.go:101 +0xe7
created by github.com/gcash/bchd/vendor/github.com/btcsuite/goleveldb/leveldb.openDB
	/home/alien/go/src/github.com/gcash/bchd/vendor/github.com/btcsuite/goleveldb/leveldb/db.go:143 +0x42e

goroutine 52 [select]:
github.com/gcash/bchd/vendor/github.com/btcsuite/goleveldb/leveldb.(*DB).tCompaction(0xc00014a820)
	/home/alien/go/src/github.com/gcash/bchd/vendor/github.com/btcsuite/goleveldb/leveldb/db_compaction.go:834 +0x331
created by github.com/gcash/bchd/vendor/github.com/btcsuite/goleveldb/leveldb.openDB
	/home/alien/go/src/github.com/gcash/bchd/vendor/github.com/btcsuite/goleveldb/leveldb/db.go:149 +0x58c

goroutine 53 [select, 303 minutes]:
github.com/gcash/bchd/vendor/github.com/btcsuite/goleveldb/leveldb.(*DB).mCompaction(0xc00014a820)
	/home/alien/go/src/github.com/gcash/bchd/vendor/github.com/btcsuite/goleveldb/leveldb/db_compaction.go:762 +0x12e
created by github.com/gcash/bchd/vendor/github.com/btcsuite/goleveldb/leveldb.openDB
	/home/alien/go/src/github.com/gcash/bchd/vendor/github.com/btcsuite/goleveldb/leveldb/db.go:150 +0x5ae
```

**Comment by The-One-Law** [comment]
Possibly related ? to Issue 2: Out of Memory after reboot:

`/home/travis/gopath/src/github.com/gcash/bchd/blockchain/utxocache.go`

Running the pre-compiled v0.14.3 on debian 9:
Following unplanned server crash now has SIGSSEGV, 
 with or without `--reindexchainstate`
perhaps not related but just in case:

VPS:

- bchd v0.14.3 ( https://github.com/gcash/bchd/releases/download/v0.14.3/bchd-linux_amd64.zip )
- debian 9 = 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u2 (2019-05-13) x86_64 GNU/Linux
- 2 cores ( nproc = 2 )
- 8GB
- 200gb SSD

```
user@retester:~$ bchd
2019-05-19 05:43:42.092 [INF] BCHD: Version 0.14.3
2019-05-19 05:43:42.093 [INF] BCHD: Loading block database from '/home/user/.bchd/data/mainnet/blocks_ffldb'
2019-05-19 05:43:43.595 [INF] BCHD: Block database loaded
2019-05-19 05:43:43.646 [INF] INDX: Transaction index is enabled
2019-05-19 05:43:43.647 [INF] INDX: Committed filter index is enabled
2019-05-19 05:43:43.651 [INF] CHAN: Loading block index...
2019-05-19 05:43:58.442 [INF] CHAN: Reconstructing UTXO state after unclean shutdown. This may take a long time...
2019-05-19 05:43:58.902 [INF] BCHD: Gracefully shutting down the database...
2019-05-19 05:43:58.940 [INF] BCHD: Shutdown complete
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x7da897]

goroutine 1 [running]:
github.com/gcash/bchd/blockchain.(*utxoCache).InitConsistentState(0xc00007a240, 0xc006226ee0, 0x0, 0xc000084120, 0x46, 0x78)
	/home/travis/gopath/src/github.com/gcash/bchd/blockchain/utxocache.go:710 +0x3a7
github.com/gcash/bchd/blockchain.New(0xc0000b4dc0, 0xc0000b4dc0, 0x18, 0x0)
	/home/travis/gopath/src/github.com/gcash/bchd/blockchain/chain.go:2263 +0x786
main.newServer(0xc000031670, 0x1, 0x1, 0xe90f00, 0xc0000a63c0, 0x140a6a0, 0xc000084120, 0xc000095c70, 0xc000095c60, 0xc0000aece0)
	/home/travis/gopath/src/github.com/gcash/bchd/server.go:3137 +0xa63
main.bchdMain(0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/gcash/bchd/bchd.go:153 +0x69f
main.main()
	/home/travis/gopath/src/github.com/gcash/bchd/bchd.go:335 +0xd0
user@retester:~$ bchd --reindexchainstate
2019-05-19 05:53:34.645 [INF] BCHD: Version 0.14.3
2019-05-19 05:53:34.646 [INF] BCHD: Loading block database from '/home/user/.bchd/data/mainnet/blocks_ffldb'
2019-05-19 05:53:36.224 [INF] BCHD: Block database loaded
2019-05-19 05:53:36.297 [INF] INDX: Transaction index is enabled
2019-05-19 05:53:36.297 [INF] INDX: Committed filter index is enabled
2019-05-19 05:53:36.299 [INF] CHAN: Loading block index...
2019-05-19 05:53:52.457 [INF] CHAN: Reconstructing UTXO state after unclean shutdown. This may take a long time...
2019-05-19 05:53:52.922 [INF] BCHD: Gracefully shutting down the database...
2019-05-19 05:53:52.945 [INF] BCHD: Shutdown complete
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x7da897]

goroutine 1 [running]:
github.com/gcash/bchd/blockchain.(*utxoCache).InitConsistentState(0xc0000a4c60, 0xc00621aee0, 0x0, 0xc000084480, 0x46, 0x78)
	/home/travis/gopath/src/github.com/gcash/bchd/blockchain/utxocache.go:710 +0x3a7
github.com/gcash/bchd/blockchain.New(0xc00013a140, 0xc00013a140, 0x18, 0x0)
	/home/travis/gopath/src/github.com/gcash/bchd/blockchain/chain.go:2263 +0x786
main.newServer(0xc00003d810, 0x1, 0x1, 0xe90f00, 0xc0000a6140, 0x140a6a0, 0xc000084480, 0xc000095a80, 0xc000095a70, 0xc0000a8b60)
	/home/travis/gopath/src/github.com/gcash/bchd/server.go:3137 +0xa63
main.bchdMain(0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/gcash/bchd/bchd.go:153 +0x69f
main.main()
	/home/travis/gopath/src/github.com/gcash/bchd/bchd.go:335 +0xd0

```

**Comment by zquestz** [comment]
We have fixed the issues with unexpected shutdowns. We can reopen if this persists.
