### ISSUE TITLE
crash entriesByBlockHashes

### ISSUE THREAD

**Issue by nshopik** [gcash/bchd#294]
got crash with that text dump
```
2019-10-26 05:30:26.168 [INF] PEER: Growing size of checkpoint cache from 0 to 606 block hashes
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8305a3]

goroutine 181260 [running]:
github.com/gcash/bchd/blockchain/indexers.(*CfIndex).entriesByBlockHashes(0x0, 0x14cb330, 0x1, 0x1, 0x200, 0xc00bcd7900, 0x25e, 0x25e, 0x10, 0x10, ...)
        /home/travis/gopath/src/github.com/gcash/bchd/blockchain/indexers/cfindex.go:348 +0x153
github.com/gcash/bchd/blockchain/indexers.(*CfIndex).FilterHeadersByBlockHashes(...)
        /home/travis/gopath/src/github.com/gcash/bchd/blockchain/indexers/cfindex.go:386
main.(*serverPeer).OnGetCFCheckpt(0xc026e540d0, 0xc01e256000, 0xc026a3b380)
        /home/travis/gopath/src/github.com/gcash/bchd/server.go:1371 +0x5f7
github.com/gcash/bchd/peer.(*Peer).inHandler(0xc01e256000)
        /home/travis/gopath/src/github.com/gcash/bchd/peer/peer.go:1602 +0x12dc
created by github.com/gcash/bchd/peer.(*Peer).start
        /home/travis/gopath/src/github.com/gcash/bchd/peer/peer.go:2268 +0x29f
```

**Comment by cpacia** [comment]
Are you running a fast synced node?

**Comment by nshopik** [comment]
yeah, fast sync enabled
