### ISSUE TITLE
Problem loading data from CIFS 

### ISSUE THREAD

**Issue by jonas-lundqvist** [gcash/bchd#367]
Background:
I am running bchd with txindex=1 and addrindex=1 and have been for quite some time, months on and off. One special thing with my setup is that I have copied most of the old ~/.bchd/data/mainnet/blocks_ffldb/\*.fdb and ~/.bchd/data/mainnet/blocks_ffldb/metadata/\*.ldb to a CIFS mounted drive and then created symbolic links to those specific files. Currently I have 000000268.fdb..000000273.fdb (each 512M) on my SSD disk and the older ones my CIFS drive with corresponding symlinks. This has worked well so far and I have started and stopped BCHD many times. I also have a similar setup with Bitcoin Core and that seems to work as intendend.

Currently I am unable to start BCHD (latest from origin/master, commite 8af7d15470b6b014). Sometimes I get the following output:

```
./bchd &
2020-05-05 14:21:33.826 [INF] BCHD: Version 0.16.0
2020-05-05 14:21:33.826 [INF] BCHD: Loading block database from '/home/jonas/.bchd/data/mainnet/blocks_ffldb'
2020-05-05 14:21:35.436 [INF] BCHD: Block database loaded
2020-05-05 14:21:35.444 [INF] INDX: Transaction index is enabled
2020-05-05 14:21:35.444 [INF] INDX: Address index is enabled
2020-05-05 14:21:35.444 [INF] INDX: Committed filter index is enabled
2020-05-05 14:21:35.445 [INF] CHAN: Loading block index...
2020-05-05 14:21:39.139 [INF] BCHD: Gracefully shutting down the database...
2020-05-05 14:21:39.154 [INF] BCHD: Shutdown complete
panic: runtime error: index out of range [567096] with length 567096 [recovered]
        panic: runtime error: index out of range [567096] with length 567096

goroutine 1 [running]:
github.com/gcash/bchd/database/ffldb.rollbackOnPanic(0xc00013ea00)
        /home/jonas/code/bchd/database/ffldb/db.go:1903 +0x77
panic(0xcf9720, 0xc000198020)
        /usr/lib/go-1.14/src/runtime/panic.go:969 +0x166
github.com/gcash/bchd/blockchain.(*BlockChain).initChainState.func2(0xff2d20, 0xc00013ea00, 0xc00013ea00, 0x0)
        /home/jonas/code/bchd/blockchain/chainio.go:1374 +0xeef
github.com/gcash/bchd/database/ffldb.(*db).View(0xc00014c000, 0xc000194300, 0x0, 0x0)
        /home/jonas/code/bchd/database/ffldb/db.go:1926 +0x99
github.com/gcash/bchd/blockchain.(*BlockChain).initChainState(0xc0006d81c0, 0xc0006d8100, 0xc0007af228, 0x2)
        /home/jonas/code/bchd/blockchain/chainio.go:1309 +0x12e
github.com/gcash/bchd/blockchain.New(0xc0007af8e0, 0x1a, 0x1a, 0x0)
        /home/jonas/code/bchd/blockchain/chain.go:2290 +0x6cd
main.newServer(0xc00058ec50, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xfe9900, ...)
        /home/jonas/code/bchd/server.go:3195 +0xa30
main.bchdMain(0x0, 0x0, 0x0)
        /home/jonas/code/bchd/bchd.go:153 +0x743
main.main()
        /home/jonas/code/bchd/bchd.go:335 +0xd0
```
Or sometimes these:
```
./bchd &
2020-05-05 14:23:15.378 [INF] BCHD: Version 0.16.0
2020-05-05 14:23:15.378 [INF] BCHD: Loading block database from '/home/jonas/.bchd/data/mainnet/blocks_ffldb'
2020-05-05 14:23:16.162 [ERR] BCHD: seek /home/jonas/.bchd/data/mainnet/blocks_ffldb/000000070.fdb: interrupted system call
2020-05-05 14:23:16.162 [INF] BCHD: Shutdown complete

```
And most oftenly these (please note that the actual file is different each time):
```
./bchd &
2020-05-05 14:23:41.831 [INF] BCHD: Version 0.16.0
2020-05-05 14:23:41.831 [INF] BCHD: Loading block database from '/home/jonas/.bchd/data/mainnet/blocks_ffldb'
2020-05-05 14:23:42.107 [ERR] BCHD: stat /home/jonas/.bchd/data/mainnet/blocks_ffldb/000000011.fdb: interrupted system call
2020-05-05 14:23:42.107 [INF] BCHD: Shutdown complete

```

Is the symlink-to-CIFS method a no-go or is there a bug somewhere in BCHD?

**Comment by zquestz** [comment]
There is nothing in BCHD that should prevent this from working. It seems to me that your CIFS mount is having odd issues, for instance there is no reason that a stat call should fail. Maybe you are hitting an open files limit or some other resource limit?

**Comment by jonas-lundqvist** [comment]
After checking out and built v0.16.0 it worked on the fifth try and now my node is up and running.
I don't dare to restart it yet :)

I'll close this issue since I am leaning towards an intermittent problem with my NAS.

**Comment by jonas-lundqvist** [comment]
After some digging this looks like an issue with asynchronous preemption that was added in golang 1.14
https://golang.org/doc/go1.14#runtime
Setting the environment variable `GODEBUG=asyncpreemptoff=1` solves this.
I am reopening this issue since there is some changes to BCHD to fix this or. At the very least it should be documented.

**Comment by zquestz** [comment]
@jonas-lundqvist thanks so much for reporting this. We should probably document this for now, and also come up with a PR that does some retrying on errors from this change. For now you can also just compile with Go 1.13 and your issues should vanish. =)
