### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by DaSpawn** [gcash/bchd#415]
I had to restart my node and now I am unable to start it again:

```

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x7bcd49]

goroutine 1 [running]:
github.com/gcash/bchd/blockchain.(*utxoCache).InitConsistentState(0xc4201c2b40, 0xc42d5736c0, 0x0, 0xc4201aa180, 0x78, 0x46)
	/home/ubuntu/go/src/github.com/gcash/bchd/blockchain/utxocache.go:728 +0x3c9
github.com/gcash/bchd/blockchain.New(0xc4201cc280, 0xc4201cc280, 0x1b, 0x0)
	/home/ubuntu/go/src/github.com/gcash/bchd/blockchain/chain.go:2300 +0x77f
main.newServer(0xc4200e8840, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xf01640, ...)
	/home/ubuntu/workspace/bchd/server.go:3196 +0xb2c
main.bchdMain(0x0, 0x0, 0x0)
	/home/ubuntu/workspace/bchd/bchd.go:153 +0x702
main.main()
	/home/ubuntu/workspace/bchd/bchd.go:335 +0xd0

```

**Comment by blockparty-sh** [comment]
I also got this after getting:

`bchd[5773]: fatal error: sync: Unlock of unlocked RWMutex`

During a reorg.

**Comment by zquestz** [comment]
Yep, this is a known issue and we are trying to get to the bottom of it. Unfortunately this code path is quite complex. =(

**Comment by zquestz** [comment]
This has been fixed!
