### ISSUE TITLE
[grpc] Security handshake failed: Cannot check peer: missing selected ALPN property when connecting to localhost

### ISSUE THREAD

**Issue by marinacabrera** [gcash/bchd#507]
### Issue

When connecting to a local node using grpc-bchrpc-node library and using a self-signed certificate generated by bchd, I get the following errors from GRPC debug logs:
` Security handshake failed: {"created":"@1653027248.283556747","description":"Cannot check peer: missing selected ALPN property.","file":"../deps/grpc/src/core/lib/security/security_connector/ssl_utils.cc","file_line":118}
.` resulting in `failed to connect to all addresses`

### Observations
I was able to change the **url** parameter in the script to **bchd.fountainhead.cash:443** and was able to get the proper response from the getBlockchainInfo method.

### test_grpc.js file
```
const { GrpcClient } = require('grpc-bchrpc-node');

const grpcConfig = {    
  url: 'localhost:8334',        
  rootCertPath: '/home/andre/bchd/rpc.cert'
}

grpc = new GrpcClient(grpcConfig);

(async () => {
  console.log(await (await grpc.getBlockchainInfo()).toObject())
})()
```

### BCHD logs

```
[andre@ip-172-31-3-183 bchd]$ tail -f logs/bchd.log 
2022-05-20 06:03:36.107 [INF] BCHD: Version 0.19.0
2022-05-20 06:03:36.107 [INF] BCHD: Loading block database from '/home/andre/bchd/data/mainnet/blocks_ffldb'
2022-05-20 06:03:36.430 [INF] BCHD: Block database loaded
2022-05-20 06:03:36.437 [INF] INDX: Committed filter index is enabled
2022-05-20 06:03:36.443 [INF] CHAN: Loading block index...
2022-05-20 06:03:44.762 [INF] CHAN: Chain state (height 436455, hash 000000000000000003e1806440f8e0777b4d6d890ecec39f413834282c533437, totaltx 166587377, work 53663255178569883100906272)
**2022-05-20 06:03:44.773 [INF] RPCS: RPC server listening on 127.0.0.1:8334**
2022-05-20 06:03:44.957 [INF] AMGR: Loaded 6973 addresses from file '/home/andre/bchd/data/mainnet/peers.json'
2022-05-20 06:03:44.958 [INF] CMGR: Server listening on 0.0.0.0:8333
2022-05-20 06:03:44.958 [INF] CMGR: Server listening on [::]:8333
2022-05-20 06:03:45.030 [INF] SYNC: New valid peer 68.73.213.74:8333 (outbound) (/Bitcoin Cash Node:23.0.1(EB32.0)/)
2022-05-20 06:03:45.030 [INF] SYNC: Syncing to block height 740238 from peer 68.73.213.74:8333
2022-05-20 06:03:45.030 [INF] SYNC: Downloading headers for blocks 436456 to 470000 from peer 68.73.213.74:8333
2022-05-20 06:03:45.087 [INF] SYNC: New valid peer 162.242.168.55:8333 (outbound) (/Bitcoin Cash Node:24.0.0(EB32.0)/)
2022-05-20 06:03:45.264 [INF] CMGR: 25 addresses found from DNS seed seed.bchd.cash
2022-05-20 06:03:45.278 [INF] SYNC: New valid peer 88.99.107.124:8333 (outbound) (/Bitcoin Cash Node:24.0.0(EB32.0)/)
2022-05-20 06:03:45.314 [INF] SYNC: New valid peer 173.212.243.103:8333 (outbound) (/BCH Unlimited:1.10.0(EB32; AD12; 64bit)/)
2022-05-20 06:03:45.442 [INF] SYNC: New valid peer 52.203.66.52:8333 (outbound) (/Bitcoin Cash Node:24.0.0(EB32.0)/)
2022-05-20 06:03:45.506 [INF] SYNC: New valid peer 185.17.143.242:8333 (outbound) (/BCH Unlimited:1.9.2(EB32; AD12; 64bit)/)
2022-05-20 06:03:45.506 [INF] SYNC: New valid peer 162.250.189.42:8333 (outbound) (/BCH Unlimited:1.9.2(EB32; AD12; 64bit)/)
2022-05-20 06:03:45.764 [INF] CMGR: 38 addresses found from DNS seed dnsseed.electroncash.de
2022-05-20 06:03:46.318 [INF] SYNC: Verified downloaded block header against checkpoint at height 470000/hash 0000000000000000006c539c722e280a0769abd510af0073430159d71e6d7589
2022-05-20 06:03:46.318 [INF] SYNC: Received 33545 block headers: Fetching blocks
2022-05-20 06:03:46.420 [INF] CMGR: 39 addresses found from DNS seed seed.bch.loping.net

```

### Running test_grpc.js file with GRPC debug flags
```
andre@ip-172-31-3-183 paybutton-server]$ GRPC_VERBOSITY=debug GRPC_TRACE=channel,subchannel,call_stream node test_grpc.js 
D0520 06:07:16.974214276   15940 dns_resolver.cc:294]        Using native dns resolver
E0520 06:07:16.974255178   15940 trace.cc:65]                Unknown trace var: 'call_stream'
I0520 06:07:17.014005787   15940 call.cc:626]                OP[client_idle:0x25018030]:  SEND_INITIAL_METADATA{key=3a 70 61 74 68 ':path' value=2f 70 62 2e 62 63 68 72 70 63 2f 47 65 74 42 6c 6f 63 6b 49 6e 66 6f '/pb.bchrpc/GetBlockInfo'}
I0520 06:07:17.014045590   15940 channel_stack.cc:226]       OP[client-channel:0x25018048]:  SEND_INITIAL_METADATA{key=3a 70 61 74 68 ':path' value=2f 70 62 2e 62 63 68 72 70 63 2f 47 65 74 42 6c 6f 63 6b 49 6e 66 6f '/pb.bchrpc/GetBlockInfo'}
D0520 06:07:17.014066718   15940 dns_resolver.cc:242]        Start resolving.
I0520 06:07:17.023588817   15940 call.cc:626]                OP[client_idle:0x251544f0]:  SEND_INITIAL_METADATA{key=3a 70 61 74 68 ':path' value=2f 70 62 2e 62 63 68 72 70 63 2f 47 65 74 42 6c 6f 63 6b 63 68 61 69 6e 49 6e 66 6f '/pb.bchrpc/GetBlockchainInfo'}
I0520 06:07:17.023624779   15940 channel_stack.cc:226]       OP[client-channel:0x25154508]:  SEND_INITIAL_METADATA{key=3a 70 61 74 68 ':path' value=2f 70 62 2e 62 63 68 72 70 63 2f 47 65 74 42 6c 6f 63 6b 63 68 61 69 6e 49 6e 66 6f '/pb.bchrpc/GetBlockchainInfo'}
D0520 06:07:17.040135272   15940 security_handshaker.cc:176] Security handshake failed: {"created":"@1653026837.040121504","description":"Cannot check peer: missing selected ALPN property.","file":"../deps/grpc/src/core/lib/security/security_connector/ssl_utils.cc","file_line":118}
I0520 06:07:17.040222426   15940 subchannel.cc:1034]         Connect failed: {"created":"@1653026837.040121504","description":"Cannot check peer: missing selected ALPN property.","file":"../deps/grpc/src/core/lib/security/security_connector/ssl_utils.cc","file_line":118}
D0520 06:07:17.040261113   15940 dns_resolver.cc:223]        In cooldown from last resolution (from 27 ms ago). Will resolve again in 29973 ms
I0520 06:07:17.040280001   15940 subchannel.cc:973]          Subchannel 0x2513a110: Retry in 985 milliseconds
I0520 06:07:17.040294147   15940 call.cc:626]                OP[client_idle:0x251544f0]:  SEND_MESSAGE:flags=0x00000000:len=0
I0520 06:07:17.040300136   15940 channel_stack.cc:226]       OP[client-channel:0x25154508]:  SEND_MESSAGE:flags=0x00000000:len=0
I0520 06:07:17.040305970   15940 call.cc:626]                OP[client_idle:0x25018030]:  SEND_MESSAGE:flags=0x00000000:len=34
I0520 06:07:17.040317925   15940 channel_stack.cc:226]       OP[client-channel:0x25018048]:  SEND_MESSAGE:flags=0x00000000:len=34
I0520 06:07:17.040324210   15940 call.cc:626]                OP[client_idle:0x251544f0]:  SEND_TRAILING_METADATA{} RECV_INITIAL_METADATA RECV_MESSAGE RECV_TRAILING_METADATA
I0520 06:07:17.040330799   15940 channel_stack.cc:226]       OP[client-channel:0x25154508]:  SEND_TRAILING_METADATA{} RECV_INITIAL_METADATA RECV_MESSAGE RECV_TRAILING_METADATA
I0520 06:07:17.040335656   15940 call.cc:626]                OP[client_idle:0x25018030]:  SEND_TRAILING_METADATA{} RECV_INITIAL_METADATA RECV_MESSAGE RECV_TRAILING_METADATA
I0520 06:07:17.040341474   15940 channel_stack.cc:226]       OP[client-channel:0x25018048]:  SEND_TRAILING_METADATA{} RECV_INITIAL_METADATA RECV_MESSAGE RECV_TRAILING_METADATA
I0520 06:07:17.040359492   15940 call.cc:626]                OP[client_idle:0x251544f0]:  CANCEL:{"created":"@1653026837.040275456","description":"Failed to pick subchannel","file":"../deps/grpc/src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1653026837.040271870","description":"failed to connect to all addresses","file":"../deps/grpc/src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}
I0520 06:07:17.040370544   15940 channel_stack.cc:226]       OP[client-channel:0x25154508]:  CANCEL:{"created":"@1653026837.040275456","description":"Failed to pick subchannel","file":"../deps/grpc/src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1653026837.040271870","description":"failed to connect to all addresses","file":"../deps/grpc/src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}
I0520 06:07:17.040389440   15940 call.cc:626]                OP[client_idle:0x25018030]:  CANCEL:{"created":"@1653026837.040276375","description":"Failed to pick subchannel","file":"../deps/grpc/src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1653026837.040271870","description":"failed to connect to all addresses","file":"../deps/grpc/src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}
I0520 06:07:17.040397949   15940 channel_stack.cc:226]       OP[client-channel:0x25018048]:  CANCEL:{"created":"@1653026837.040276375","description":"Failed to pick subchannel","file":"../deps/grpc/src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1653026837.040271870","description":"failed to connect to all addresses","file":"../deps/grpc/src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}
/home/andre/paybutton-server/node_modules/grpc/src/common.js:91
  let error = new Error(message);
              ^

Error: 14 UNAVAILABLE: failed to connect to all addresses
    at Object.exports.createStatusError (/home/andre/paybutton-server/node_modules/grpc/src/common.js:91:15)
    at Object.onReceiveStatus (/home/andre/paybutton-server/node_modules/grpc/src/client_interceptors.js:1209:28)
    at InterceptingListener._callNext (/home/andre/paybutton-server/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/home/andre/paybutton-server/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (/home/andre/paybutton-server/node_modules/grpc/src/client_interceptors.js:847:24) {
  code: 14,
  metadata: Metadata { _internal_repr: {}, flags: 0 },
  details: 'failed to connect to all addresses'
}

```

**Comment by alcipir** [comment]
Following the client example from BCHD's documentation (with small modifications to use insecure credentials), with TLS disabled on BCHD:

### from nodejs client docs (no tls)
```
var PROTO_PATH = __dirname + '/bchrpc.proto';

var grpc = require('@grpc/grpc-js');
var protoLoader = require('@grpc/proto-loader');
var packageDefinition = protoLoader.loadSync(
    PROTO_PATH,
    {
        keepCase: true,
        longs: String,
        enums: String,
        defaults: true,
        oneofs: true
    });

var pb = grpc.loadPackageDefinition(packageDefinition).pb;
var client = new pb.bchrpc('localhost:8334', grpc.credentials.createInsecure());


// Get current state of the mempool
client.GetMempoolInfo(pb.MempoolInfoRequest, function(error, resp) {
    if (error) {
        console.log("Error: " + error.code + ": " + error.message)
        console.log(error)
    } else {
    var mempool = resp
    console.log("\nGetMempoolInfo:")
    console.log(mempool)
    }
});
```

### node index.js logs with GRPC_VERBOSITY=debug and GRPC_TRACE=all
```
Error: 13: 13 INTERNAL: Received RST_STREAM with code 2 triggered by internal client error: Protocol error
Error: 13 INTERNAL: Received RST_STREAM with code 2 triggered by internal client error: Protocol error
    at Object.callErrorFromStatus (/home/andre/grpc-test/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
    at Object.onReceiveStatus (/home/andre/grpc-test/node_modules/@grpc/grpc-js/build/src/client.js:189:52)
    at Object.onReceiveStatus (/home/andre/grpc-test/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:365:141)
    at Object.onReceiveStatus (/home/andre/grpc-test/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:328:181)
    at /home/andre/grpc-test/node_modules/@grpc/grpc-js/build/src/call-stream.js:187:78
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  code: 13,
  details: 'Received RST_STREAM with code 2 triggered by internal client error: Protocol error',
  metadata: Metadata { internalRepr: Map(0) {}, options: {} }

```


With proper credentials/cert file, it throws the same SSL error as before with my own script.

**Comment by zquestz** [comment]
Sorry for the delayed reply.

There are docs on how to do this at https://github.com/simpleledgerinc/grpc-bchrpc-node

You just need to make sure you pass in the cert you used for the server on the client side.
