### ISSUE TITLE
panic runtime error

### ISSUE THREAD

**Issue by Azulan** [gcash/bchd#509]
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x38 pc=0xb99fd3]

goroutine 33 [running]:
github.com/gcash/bchd/database/ffldb.rollbackOnPanic(0xc000503860)
        /home/quest/go/src/github.com/gcash/bchd/database/ffldb/db.go:1903 +0x5b
panic({0xf50de0, 0x17e75e0})
        /usr/lib/go/src/runtime/panic.go:838 +0x207
github.com/gcash/bchd/database/ffldb.(*blockStore).writeData(0xc00fdad940?, {0xc01065e420?, 0x30?, 0x30?}, {0x105d299, 0x11})
        /home/quest/go/src/github.com/gcash/bchd/database/ffldb/blockio.go:387 +0x53
github.com/gcash/bchd/database/ffldb.(*blockStore).writeBlock(0xc000254000, {0xc011082000, 0xdba27, 0xdba27}, 0xb693c)
        /home/quest/go/src/github.com/gcash/bchd/database/ffldb/blockio.go:433 +0xef
github.com/gcash/bchd/database/ffldb.(*transaction).writePendingAndCommit(0xc000503860)
        /home/quest/go/src/github.com/gcash/bchd/database/ffldb/db.go:1685 +0x19c
github.com/gcash/bchd/database/ffldb.(*transaction).Commit(0x12cff40?)
        /home/quest/go/src/github.com/gcash/bchd/database/ffldb/db.go:1758 +0xda
github.com/gcash/bchd/database/ffldb.(*db).Update(0xc00057e540?, 0xc00e933d70)
        /home/quest/go/src/github.com/gcash/bchd/database/ffldb/db.go:1970 +0xe9
github.com/gcash/bchd/blockchain.(*BlockChain).maybeAcceptBlock(0xc00057e540, 0xc002ecd590, 0xc00e6a8104, 0xc00f324af0, 0x4?)
        /home/quest/go/src/github.com/gcash/bchd/blockchain/accept.go:55 +0xf5
github.com/gcash/bchd/blockchain.(*BlockChain).ProcessBlock(0xc00057e540, 0xc002ecd590, 0x0)
        /home/quest/go/src/github.com/gcash/bchd/blockchain/process.go:218 +0x25c
github.com/gcash/bchd/netsync.(*SyncManager).handleBlockMsg(0xc000506180, 0xc0027eecc0)
        /home/quest/go/src/github.com/gcash/bchd/netsync/manager.go:850 +0x3ca
github.com/gcash/bchd/netsync.(*SyncManager).blockHandler(0xc000506180)
        /home/quest/go/src/github.com/gcash/bchd/netsync/manager.go:1499 +0x4ed
created by github.com/gcash/bchd/netsync.(*SyncManager).Start
        /home/quest/go/src/github.com/gcash/bchd/netsync/manager.go:1759 +0xca
```

**Comment by BrannonKing** [comment]
Did you run out of drive space?

**Comment by binarystorm** [comment]
Runtime error here also.

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x80f404]

goroutine 67959 [running]:
github.com/gcash/bchd/blockchain/indexers.(*CfIndex).entriesByBlockHashes(0x0, {0x14aba70?, 0xc00f9d0038?, 0x7d1?}, 0xc7?, {0xc013fc8030, 0x2, 0x2})
        /home/quest/go/src/github.com/gcash/bchd/blockchain/indexers/cfindex.go:383 +0x164
github.com/gcash/bchd/blockchain/indexers.(*CfIndex).FilterHashesByBlockHashes(...)
        /home/quest/go/src/github.com/gcash/bchd/blockchain/indexers/cfindex.go:435
main.(*serverPeer).OnGetCFHeaders(0xc0002701c0, 0xc0182eae01?, 0xc00f9d0030)
        /home/quest/go/src/github.com/gcash/bchd/server.go:1216 +0x365
github.com/gcash/bchd/peer.(*Peer).inHandler(0xc018b5fc00)
        /home/quest/go/src/github.com/gcash/bchd/peer/peer.go:1629 +0x11e6
created by github.com/gcash/bchd/peer.(*Peer).start
        /home/quest/go/src/github.com/gcash/bchd/peer/peer.go:2361 +0x2bc

**Comment by zquestz** [comment]
There are two different panics in this thread and both are now fixed.

@Azulan's is the block file rollover crash, the same one as #401. When a block pushes the store into a new flat file, the height of the last block is written to the end of the current file first, and that write happened before the code that opens the file. The file is legitimately closed at that point after an initial load or a rollback, so it dereferenced nil. @BrannonKing's disk space guess was reasonable but not the cause. Worth noting the panic occurred while holding the file lock with no deferred unlock, so `rollbackOnPanic` would recover and leave the process alive with the database wedged, which is probably nastier than the crash itself.

@binarystorm's is unrelated. The committed filter handlers dereferenced `cfIndex` without checking it exists. The index is skipped under either `--nocfilters` or `--fastsync`, but only `--nocfilters` cleared the `NODE_CF` service bit, so a fastsync node advertised committed filter support and then panicked on the first `getcfheaders` it received. If you were running `--fastsync`, that is what you hit.

That one is worse than a config mismatch: the service bit is only a hint, so any peer could send the message and crash the node regardless of what we advertise. All three handlers now check the index first, and `NODE_CF` is no longer advertised when the index is not maintained.

Both fixes will be in the next release.
